---
kind: pipeline
type: kubernetes
name: commit-main

trigger:
  ref:
    - refs/heads/main

steps:
  - name: trigger-downstream
    image: plugins/downstream
    settings:
      server:
        from_secret: droneServer
      token:
        from_secret: droneToken
      fork: true
      wait: true
      repositories:
        - MCT/mct-hpc-jupyter@main
