---
kind: pipeline
type: docker
name: hdf5container-build-wheel

# drone exec --trusted --timeout 10h --secret-file secrets.txt  .drone/.drone-local.yml

steps:
  - name: download-archive
    image: minio/mc
    environment:
      MINIO_HOST: https://s3-api.asci.synchrotron.org.au
      MINIO_USERNAME:
        from_secret: MINIO_USERNAME
      MINIO_PASSWORD:
        from_secret: MINIO_PASSWORD
      MINIO_BUCKET: beamline-mct
    commands:
      - rm -rf ITK_build_resources
      - mc alias set minio $MINIO_HOST $MINIO_USERNAME $MINIO_PASSWORD
      - mc cp --recursive minio/$MINIO_BUCKET/ITK_build_resources/ ITK_build_resources/

  - name: setup-itkpythonpackage
    image: alpine
    environment:
      ITK_PYTHON_PACKAGE_REPO: https://github.com/InsightSoftwareConsortium/ITKPythonPackage.git
      ITK_PACKAGE_VERSION: 5.4.0
      MANYLINUX_VERSION: manylinux_2_28_x64
    commands:
      - apk add --no-cache git sed zstd tar
      - rm -rf dist ITK-* _skbuild *.egg-info tools oneTBB-prefix itk ITKPythonPackage
      - git clone --depth 1 --branch v$ITK_PACKAGE_VERSION $ITK_PYTHON_PACKAGE_REPO ITKPythonPackage
      - tar --use-compress-program=unzstd -xf ITK_build_resources/ITKPythonBuilds-$MANYLINUX_VERSION-v$ITK_PACKAGE_VERSION.tar.zst ITKPythonPackage/scripts/ ITKPythonPackage/oneTBB-prefix/ ITKPythonPackage/ITK-source/ --wildcards ITKPythonPackage/ITK-*
      - rm ITK_build_resources/ITKPythonBuilds-$MANYLINUX_VERSION-v$ITK_PACKAGE_VERSION.tar.zst
      - ln -s ITKPythonPackage/oneTBB-prefix
      - cp .drone/ITKPythonPackage/CMakeLists.txt ITKPythonPackage
      - .drone/ITKPythonPackage/set_itk_version.sh $ITK_PACKAGE_VERSION
      - cp .drone/ITKPythonPackage/requirements.txt ITKPythonPackage
      - sed -i "/^VERSION = /c\VERSION = '$ITK_PACKAGE_VERSION'" ITKPythonPackage/itkVersion.py
      - cp .drone/ITKPythonPackage/dockcross-manylinux-build-module-wheels.sh ITKPythonPackage/scripts
      - cp .drone/ITKPythonPackage/manylinux-build-common.sh ITKPythonPackage/scripts/internal
      - cp .drone/ITKPythonPackage/manylinux-build-module-wheels.sh ITKPythonPackage/scripts/internal

  - name: build-wheel
    image: docker:dind
    environment:
      MANYLINUX_VERSION: manylinux_2_28
      MANYLINUX_ARCH: x64
      MANYLINUX_TAG: 20240729-13d3b71
      PYTHON_VERSIONS: cp311
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5 # give docker enough time to start
      - apk add --no-cache bash # Install various utils
      - /bin/bash -c "ITKPythonPackage/scripts/dockcross-manylinux-build-module-wheels.sh -v$MANYLINUX_VERSION -a$MANYLINUX_ARCH -t$MANYLINUX_TAG -c -DBOOST_ROOT:PATH=/work/tools/boost $PYTHON_VERSIONS"

  - name: publish-package
    image: plugins/pypi
    settings:
      repository: https://pypi.asci.synchrotron.org.au/mct/dev/
      username:
        from_secret: PYPI_USERNAME
      password:
        from_secret: PYPI_PASSWORD
      distributions:
        - bdist_wheel
      skip_build: true

  - name: cleanup
    image: alpine
    commands:
      - rm -rf dist ITK-* _skbuild *.egg-info tools oneTBB-prefix itk ITKPythonPackage ITK_build_resources

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
